package lcs.prs.goingmobile.entities;
// Generated Aug 19, 2016 11:55:51 AM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Addresses generated by hbm2java
 */
@Entity
@Table(name = "addresses", catalog = "goingmobile")
public class Addresse implements java.io.Serializable {

	private Integer id;
	private Admin admins;
	private Client clients;
	private Partner partners;
	private String streetName;
	private String streetNumber;
	private String box;
	private String postCode;
	private String country;
	private String coordinates;
	private Date addedDate;
	private String addressType;

	public Addresse() {
	}

	public Addresse(String streetName, String streetNumber, String postCode, String country, Date addedDate,
			String addressType) {
		this.streetName = streetName;
		this.streetNumber = streetNumber;
		this.postCode = postCode;
		this.country = country;
		this.addedDate = addedDate;
		this.addressType = addressType;
	}

	public Addresse(Admin admins, Client clients, Partner partners, String streetName, String streetNumber,
			String box, String postCode, String country, String coordinates, Date addedDate, String addressType) {
		this.admins = admins;
		this.clients = clients;
		this.partners = partners;
		this.streetName = streetName;
		this.streetNumber = streetNumber;
		this.box = box;
		this.postCode = postCode;
		this.country = country;
		this.coordinates = coordinates;
		this.addedDate = addedDate;
		this.addressType = addressType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Admin_Id")
	public Admin getAdmins() {
		return this.admins;
	}

	public void setAdmins(Admin admins) {
		this.admins = admins;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Client_Id")
	public Client getClients() {
		return this.clients;
	}

	public void setClients(Client clients) {
		this.clients = clients;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Partner_Id")
	public Partner getPartners() {
		return this.partners;
	}

	public void setPartners(Partner partners) {
		this.partners = partners;
	}

	@Column(name = "streetName", nullable = false, length = 45)
	public String getStreetName() {
		return this.streetName;
	}

	public void setStreetName(String streetName) {
		this.streetName = streetName;
	}

	@Column(name = "streetNumber", nullable = false, length = 10)
	public String getStreetNumber() {
		return this.streetNumber;
	}

	public void setStreetNumber(String streetNumber) {
		this.streetNumber = streetNumber;
	}

	@Column(name = "box", length = 10)
	public String getBox() {
		return this.box;
	}

	public void setBox(String box) {
		this.box = box;
	}

	@Column(name = "postCode", nullable = false, length = 10)
	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	@Column(name = "Country", nullable = false, length = 20)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "Coordinates", length = 45)
	public String getCoordinates() {
		return this.coordinates;
	}

	public void setCoordinates(String coordinates) {
		this.coordinates = coordinates;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "addedDate", nullable = false, length = 10)
	public Date getAddedDate() {
		return this.addedDate;
	}

	@Override
	public String toString() {
		return streetName + ", " + streetNumber + "/" + box
				+ ", "+ postCode + ", " + country;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	@Column(name = "addressType", nullable = false, length = 20)
	public String getAddressType() {
		return this.addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

}
