package lcs.prs.goingmobile.entities;
// Generated Aug 19, 2016 11:55:51 AM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Admins generated by hbm2java
 */
@Entity
@Table(name = "admins", catalog = "goingmobile")
public class Admin implements java.io.Serializable {

	private Integer id;
	private String username;
	private String email;
	private String firstName;
	private String lastName;
	private String password;
	private boolean isActive;
	private Date registrationDate;
	private String profilePicture;
	private String remark;
	private String authorizationRole;
	private Set<Addresse> addresseses = new HashSet<Addresse>(0);

	public Admin() {
	}

	public Admin(String username, String email, String firstName, String lastName, String password, boolean isActive,
			Date registrationDate, String authorizationRole) {
		this.username = username;
		this.email = email;
		this.firstName = firstName;
		this.lastName = lastName;
		this.password = password;
		this.isActive = isActive;
		this.registrationDate = registrationDate;
		this.authorizationRole = authorizationRole;
	}

	public Admin(String username, String email, String firstName, String lastName, String password, boolean isActive,
			Date registrationDate, String profilePicture, String remark, String authorizationRole,
			Set<Addresse> addresseses) {
		this.username = username;
		this.email = email;
		this.firstName = firstName;
		this.lastName = lastName;
		this.password = password;
		this.isActive = isActive;
		this.registrationDate = registrationDate;
		this.profilePicture = profilePicture;
		this.remark = remark;
		this.authorizationRole = authorizationRole;
		this.addresseses = addresseses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 20)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "email", nullable = false, length = 40)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "firstName", nullable = false, length = 20)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", nullable = false, length = 20)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "password", nullable = false, length = 200)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "isActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "registrationDate", nullable = false, length = 10)
	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	@Column(name = "profilePicture")
	public String getProfilePicture() {
		return this.profilePicture;
	}

	public void setProfilePicture(String profilePicture) {
		this.profilePicture = profilePicture;
	}

	@Column(name = "remark", length = 45)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "authorizationRole", nullable = false, length = 10)
	public String getAuthorizationRole() {
		return this.authorizationRole;
	}

	public void setAuthorizationRole(String authorizationRole) {
		this.authorizationRole = authorizationRole;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admins")
	public Set<Addresse> getAddresseses() {
		return this.addresseses;
	}

	public void setAddresseses(Set<Addresse> addresseses) {
		this.addresseses = addresseses;
	}

}
